api/urls.py
from django.urls import path,include
from .views import AricleList,Article_detail,UserList,UserDetail

app_name="api"
urlpatterns=[
    path("", AricleList.as_view(), name='list'),
    path("<int:pk>", Article_detail.as_view(), name='detail'),
    path("user", UserList.as_view(), name='listuser'),
    path("user/<int:pk>", UserDetail.as_view(), name='detailuser'),
]

blog/urls.py
from  . import views
from django.urls import path
app_name="blog"
urlpatterns=[

    path("",views.blog_list,name="blog_list"),
    path("<int:id>/",views.blog_detail,name="detail"),
    path("tag/<slug:tag>",views.blog_tag,name="tag"),
    path("category/<slug:category>",views.blog_category,name="category_name"),
    path("search/",views.search,name="search")
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('book/',include('reservation.urls')),
    path('blog/',include('blog.urls')),
    path('api-auth/',include('rest_framework.urls')),
    path('api/',include('api.urls')),
    path('api-token-auth/',obtain_auth_token),
    path('get/',include('get.urls')),


               ]
urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext as gt
from ckeditor.fields import RichTextField
# Create your models here.
class   blog(models.Model):
        name = models.CharField(gt("نام مقاله"),max_length=100, default=None)
        description = models.CharField(gt("توضیحات"), max_length=100, default=None)
        content = RichTextField(blank=False,null=False)
        author = models.ForeignKey(User,verbose_name=gt("نویسنده"), on_delete=models.CASCADE)
        pub_date = models.DateTimeField(gt("تاریخ انتشار"), default=timezone.now)
        photo = models.ImageField(gt("تصویر"), upload_to="blog/", default=None)
        category=models.ForeignKey("category",related_name="blog",verbose_name="دسته بندی" ,on_delete=models.CASCADE,null=True,blank=True )
        tag=models.ManyToManyField("tag",related_name="blogs",verbose_name="تگ")
        def __str__(self):
                return self.name
class category(models.Model):
        title=models.CharField(gt("نام دسته بندی"),max_length=30)
        slug=models.SlugField(gt("نامک"))
        date=models.DateTimeField(gt("تاریخ انتشار"),auto_now=False,auto_now_add=True)
        def __str__(self):
                return self.title
class tag(models.Model):
        title=models.CharField(gt("نام تگ"),max_length=30)
        slug=models.SlugField(gt("نامک"))
        date=models.DateTimeField(gt("تاریخ انتشار"),auto_now=False,auto_now_add=True)
        def __str__(self):
                return self.title
class comments(models.Model):
        blog=models.ForeignKey("blog",related_name="blog",verbose_name="بلاگ" ,on_delete=models.CASCADE,null=True,blank=True)
        name=models.CharField(gt("نام "),max_length=30)
        email=models.EmailField(gt("ایمیل"),default="mail@gmail.com" )
        message=models.TextField(gt("نظر"))
        date=models.DateTimeField(gt("تاریخ انتشار"),auto_now=False,auto_now_add=True)

        def __str__(self):
                return self.email

blog/forms.py
from  django import forms

class CommentForm(forms.Form):
        name=forms.CharField(max_length=20)
        email=forms.EmailField(max_length=254)
        message=forms.CharField(widget=forms.Textarea)

blog/views.py
from django.shortcuts import render
from .models import blog,tag,category,comments
from .forms import CommentForm
from django.core.paginator import Paginator
# Create your views here.
def blog_list(request):
    blog_list=blog.objects.all()
    paginator = Paginator(blog_list, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context={
        "blogs":page_obj
    }
    return  render(request,"blog/blog.html",context)
def blog_detail(requset,id):
    blog_detail=blog.objects.get(id=id)
    tags = tag.objects.all().filter(blogs=blog_detail)   #?????
    rencent=blog.objects.all().order_by("pub_date")[:3]
    categories=category.objects.all()
    comment=comments.objects.all().filter(blog=blog_detail)
    if requset.method=="POST":
        form=CommentForm(requset.POST)
        if form.is_valid():
            new_name=form.cleaned_data['name']
            new_email=form.cleaned_data['email']
            new_message=form.cleaned_data['message']
            new_comment=comments(blog=blog_detail,name=new_name,email=new_email,message=new_message)
            new_comment.save()

    context={
              "detail_blogs":blog_detail,
                "tags": tags,
                "recents" : rencent,
                "category" :categories,
                "comments" : comment
            }
    return render(requset,"blog/blog-details.html",context)
def blog_tag(request,tag):
    blog_list = blog.objects.filter(tag__slug=tag)

    context = {
        "blogs": blog_list
    }
    return render(request, "blog/blog.html", context)

def blog_category(request,category):
    blog_list = blog.objects.filter(category__slug=category)

    context = {
        "blogs": blog_list
    }
    return render(request, "blog/blog.html", context)
def search(request):
    if request.method == "GET":
        q=request.GET.get("search")
    blog_list=blog.objects.filter(content__icontains=q)
    context={"blog_list":blog_list}
    return render(request,"blog/blog.html",context)

blog/templates/blog/blog-details.html
{% extends "base.html" %}
{%  block  content %}
	
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog details -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>بلاگ</h2>
						<p>محتوای آموزشی بلاگ</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-12">
					<div class="blog-inner-details-page">
						<div class="blog-inner-box">
							<div class="side-blog-img">
								<img class="img-fluid" src="{{ detail_blogs.photo.url }}" alt="">
								<div class="date-blog-up">
									27 Fab
								</div>
							</div>
							<div class="inner-blog-detail details-page">
								<h3>{{ detail_blogs.name}}</h3>
								<ul>
									<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{ detail_blogs.author.first_name}}</span></li>
									<li>|</li>
									<li><i class="zmdi zmdi-time"></i>Time : <span>{{detail_blogs.pub_date}}</span></li>
								</ul>
								<p dir="rtl">{{ detail_blogs.content }}.</p>

								<blockquote>
									<p>{{ detail_blogs.description }}.</p>
								</blockquote>

							</div>
						</div>
						<div class="blog-comment-box">
							<h3>Comments</h3>
                             {% for cm in comments %}
							<div class="comment-item">

								<div class="comment-item-left">
									<img src="images/avt-img.jpg" alt="">
								</div>
								<div class="comment-item-right">
									<div class="pull-left">
										<a href="#">{{ cm.name }}</a>
									</div>
									<div class="pull-right">
										<i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>{{ cm.date}}</span>
									</div>
									<div class="des-l">
										<p> {{ cm.message}}</p>
									</div>
									<a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
								</div>
							</div>
							<div class="comment-item children">
								<div class="comment-item-left">
									<img src="images/avt-img.jpg" alt="">
								</div>
								<div class="comment-item-right">
									<div class="pull-left">
										<a href="#">Admin</a>
									</div>
									<div class="pull-right">
										<i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>1.30 pm</span>
									</div>
									<div class="des-l">
										<p>Morbi lacinia ultrices lorem id tincidunt. Cras id dui risus. Pellentesque consectetur id mi sed pharetra. Proin imperdiet gravida nisl, sit amet varius urna. In auctor.</p>
									</div>
									<a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
								</div>
							</div>

						</div>
                        {% endfor %}
						<div class="comment-respond-box">
							<h3>Leave your comment </h3>
							<div class="comment-respond-form">
								<form id="commentrespondform" class="comment-form-respond row" method="post">
                                    {% csrf_token %}
									<div class="col-lg-6 col-md-6 col-sm-6">
										<div class="form-group">
											<input id="name_com" class="form-control" name="name" placeholder="Name" type="text">
										</div>
										<div class="form-group">
											<input id="email_com" class="form-control" name="email" placeholder="Your Email" type="email">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6">
										<div class="form-group">
											<textarea class="form-control" id="textarea_com" name="message" placeholder="Your Message" rows="2"></textarea>
										</div>
									</div>
									<div class="col-lg-12 col-md-12 col-sm-12">
										<button class="btn btn-submit" >Submit comment</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			
				<div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
					<div class="right-side-blog">
						<h3>Search</h3>
                        <form method="get" action="{% url 'blog:search' %}">
						<div class="blog-search-form">
							<input name="search" placeholder="Search blog" type="text">
							<button class="search-btn" type="submit">
								<i class="fa fa-search" aria-hidden="true"></i>
							</button>
						</div>
                        </form>
						<h3>دسته بندی</h3>
						<div class="blog-categories">
							<ul>
                                {% for cat in category %}
								<li><a href="{% url "blog:category_name"  cat.slug %}"><span>{{ cat.title}}</span></a></li>
                                {% endfor %}
							</ul>
						</div>
						<h3>Recent Post</h3>
						<div class="post-box-blog">
							<div class="recent-post-box">

								<div class="recent-box-blog">
                                    {% for recent in recents %}
									<div class="recent-img">

										<img class="img-fluid" src="{{recent.photo.url }}"  style="height: 60px" alt="">
									</div>
									<div class="recent-info">
										<ul>
											<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{ recent.author}}</span></li>
											<li>|</li>
											<li><i class="zmdi zmdi-time"></i>Time : <span>{{ recent.pub_date}}</span></li>

										</ul>
										<h4>{{ recent.description}}</h4>
									</div>
                                    {% endfor %}
								</div>

							</div>
						</div>
						<h3>Recent Tag</h3>
						<div class="blog-tag-box">
							<ul class="list-inline tag-list">
                                {% for tag in tags %}
								<li class="list-inline-item"><a href="{% url "blog:tag" tag.slug %}">{{ tag.title }}</a></li>
                                {% endfor %}
							</ul>
						</div>
					</div>
				</div>
			
			</div>
		</div>
	</div>
	<!-- End details -->
	
	<!-- Start Contact info -->
	<div class="contact-imfo-box">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<i class="fa fa-volume-control-phone"></i>
					<div class="overflow-hidden">
						<h4>Phone</h4>
						<p class="lead">
							+01 123-456-4590
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-envelope"></i>
					<div class="overflow-hidden">
						<h4>Email</h4>
						<p class="lead">
							yourmail@gmail.com
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-map-marker"></i>
					<div class="overflow-hidden">
						<h4>Location</h4>
						<p class="lead">
							800, Lorem Street, US
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Contact info -->
	
{% endblock %}

blog/templates/blog/blog.html
{% extends "base.html" %}
{%  block  content %}
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>بلاگ</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start blog -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>بلاگ</h2>
						<p>محتوای آموزشی کافه رستاد</p>
					</div>
				</div>
			</div>
			<div class="row">
                {% for blog in blogs %}
				<div class="col-lg-4 col-md-6 col-12">
					<div class="blog-box-inner">
						<div class="blog-img-box">
							<img class="img-fluid" src="{{ blog.photo.url }}"  style="height: 420px" alt="">
						</div>
						<div class="blog-detail">
							<h4>{{ blog.name}}</h4>
							<ul>
								<li><span>{{ blog.author}}</span></li>
								<li>|</li>
								<li><span>{{ blog.pub_date|date:"y b d"}}</span></li>
							</ul>

							<p dir="rtl">{{ blog.description|truncatewords:60 }} </p>
							<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blog:detail' blog.id %} ">Read More</a>
						</div>
					</div>
				</div>
			    {% endfor %}
			</div>
		</div>
	</div>
	<!-- End blog -->
    {% if blogs.has_other_pages  %}
	<div class="container mb-3">
    <div class="row">
        <div class="col d-flex justify-content-center">
            <nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if blogs.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{blogs.previous_page_number}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
          <li class="page-item">
      <a class="page-link" href="?page=1">  avalin
      </a></li>
    {% endif  %}
    {% for page in blogs.paginator.page_range %}
        {% if blogs.number == page %}
    <li class="page-item active">
        <a class="page-link" href="?page={{page}}">{{ page }}</a>
    </li>
        {%  else %}
            <li class="page-item">
                 <a class="page-link" href="?page={{page}}">{{ page }}</a>
            </li>
        {% endif %}
    {% endfor %}
    {% if blogs.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{blogs.next_page_number}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
        <li class="page-item">
      <a class="page-link" href="?page={{blogs.paginator.num_pages}}">  akharin
      </a></li>
        {% endif %}
  </ul>
</nav>
        </div>
    </div>

    </div>
    {% endif %}
	<!-- Start Contact info -->
	<div class="contact-imfo-box">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<i class="fa fa-volume-control-phone"></i>
					<div class="overflow-hidden">
						<h4>Phone</h4>
						<p class="lead">
							+01 123-456-4590
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-envelope"></i>
					<div class="overflow-hidden">
						<h4>Email</h4>
						<p class="lead">
							yourmail@gmail.com
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-map-marker"></i>
					<div class="overflow-hidden">
						<h4>Location</h4>
						<p class="lead">
							800, Lorem Street, US
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- End Contact info -->
{% endblock %}