api/urls.py
from django.urls import path,include
from .views import AricleList,Article_detail,UserList,UserDetail

app_name="api"
urlpatterns=[
    path("", AricleList.as_view(), name='list'),
    path("<int:pk>", Article_detail.as_view(), name='detail'),
    path("user", UserList.as_view(), name='listuser'),
    path("user/<int:pk>", UserDetail.as_view(), name='detailuser'),
]

blog/urls.py
from  . import views
from django.urls import path
app_name="blog"
urlpatterns=[

    path("",views.blog_list,name="blog_list"),
    path("<int:id>/",views.blog_detail,name="detail"),
    path("tag/<slug:tag>",views.blog_tag,name="tag"),
    path("category/<slug:category>",views.blog_category,name="category_name"),
    path("search/",views.search,name="search")
]

food/urls.py
from . import views
from  .views import food_detail
from django.urls import path
app_name="food"
urlpatterns=[

    path("",views.food_list,name="food_list"),
  #  path("<int:id>/",views.food_detail,name="detail")
    path("<int:id>/",food_detail.as_view(),name="detail")
]

reservation/urls.py
from django.urls import path
from .import views
app_name="reservation"

urlpatterns= [
    path('',views.reserve,name="book")
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('book/',include('reservation.urls')),
    path('blog/',include('blog.urls')),
    path('api-auth/',include('rest_framework.urls')),
    path('api/',include('api.urls')),
    path('api-token-auth/',obtain_auth_token),
    path('get/',include('get.urls')),


               ]
urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

templates/partial/_footer.html
{% load static %}
<!-- Start Footer -->
	<footer class="footer-area bg-f">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<h3>درباره ما</h3>
					<p> بچه های خوبی هستیم خخخخ</p>
				</div>
				<div class="col-lg-3 col-md-6">
					<h3>ساعت کاری</h3>
					<p><span class="text-color">:جمعه  </span>بسته</p>
					<p><span class="text-color">شنبه تا چهارشنبه :</span> 9صبح - 10شب</p>
					<p><span class="text-color">پنج شنبه :</span> 10صبح - 10شب</p>

				</div>
				<div class="col-lg-3 col-md-6">
					<h3>اطلاعات تماس</h3>
					<p class="lead"> چهار راه ولیعصر</p>
					<p class="lead"><a href="#">+920254889636</a></p>
					<p><a href="#"> info@admin.com</a></p>
				</div>
				<div class="col-lg-3 col-md-6">
					<h3>عضویت در خبرنامه</h3>
					<div class="subscribe_form">
						<form class="subscribe_form">
							<input name="EMAIL" id="subs-email" class="form_input" placeholder="Email Address..." type="email">
							<button type="submit" class="submit">عضویت</button>
							<div class="clearfix"></div>
						</form>
					</div>
					<ul class="list-inline f-social">
						<li class="list-inline-item"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<p class="company-name">تمامی حقوق برای کافه رستاد محفوظ است &copy; 2018 <a href="#">کافه رستاد</a> طراحی :
					<a href="https://html.design/">حامد حسن زاده</a></p>
					</div>
				</div>
			</div>
		</div>

	</footer>
	<!-- End Footer -->

	<a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

	<!-- ALL JS FILES -->
	<script src="{% static  "jquery-3.2.1.min.js" %}"></script>
	<script src="{% static  "js/popper.min.js"  %}"></script>
	<script src="{% static  "js/bootstrap.min.js" %}"></script>
    <!-- ALL PLUGINS -->
	<script src="{% static "js/jquery.superslides.min.js" %}"></script>
	<script src="{% static "js/images-loded.min.js" %}"></script>
	<script src="{% static "js/isotope.min.js" %}"></script>
	<script src="{% static "js/baguetteBox.min.js" %}"></script>
	<script src="{% static "js/form-validator.min.js" %}"></script>
    <script src="{% static "js/contact-form-script.js" %}"></script>
    <script src="{% static "js/custom.js" %}"></script>

templates/partial/_header.html
<!-- Start header -->
{% load static %}
	<header class="top-navbar">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="index.html">
					<img src="{% static "images/logo.png" %}" alt="" />
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbars-rs-food">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active"><a class="nav-link" href="{% url "food:food_list" %}">صفحه اصلی</a></li>
						<li class="nav-item"><a class="nav-link" href="menu.html">منو</a></li>
						<li class="nav-item"><a class="nav-link" href="about.html">درباره ما</a></li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="{% url "reservation:book" %}" id="dropdown-a" data-toggle="dropdown">صفحه ها</a>
							<div class="dropdown-menu" aria-labelledby="dropdown-a">
								<a class="dropdown-item" href="reservation.html">زرو میز</a>
								<a class="dropdown-item" href="stuff.html">کارکنان</a>
								<a class="dropdown-item" href="gallery.html">گالری</a>
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="{% url "blog:blog_list" %}" id="dropdown-a" data-toggle="dropdown">بلاگ</a>
							<div class="dropdown-menu" aria-labelledby="dropdown-a">
								<a class="dropdown-item" href="{% url "blog:blog_list" %}">">وبلاگ</a>
								<a class="dropdown-item" href="blog-details.html">تک صفحه</a>
							</div>
						</li>
						<li class="nav-item"><a class="nav-link" href="{% url "blog:blog_list" %}">تماس با ما</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<!-- End header -->